# Терминал Luna Linux. Палитра общая с панелью и Hyprland.

font_family      JetBrains Mono
font_size        11.0

# Лёгкая прозрачность: под окном видно размытый фон Hyprland.
background_opacity 0.92
background_blur    1

window_padding_width 10
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 10000

# Прокрутка в less по Ctrl+Shift+H — удобно искать в длинном выводе.
map ctrl+shift+h show_scrollback

foreground #e8e4f4
background #12111a
cursor     #b4a0ff
selection_background #2a2739
selection_foreground #e8e4f4

color0  #1b1926
color8  #2a2739
color1  #ff92a8
color9  #ff92a8
color2  #9de8b8
color10 #9de8b8
color3  #ffd79a
color11 #ffd79a
color4  #8bd5ff
color12 #8bd5ff
color5  #b4a0ff
color13 #b4a0ff
color6  #8bd5ff
color14 #8bd5ff
color7  #e8e4f4
color15 #ffffff
