#!/usr/bin/env bash
# Builds the branding images from their SVG sources.
#
# The sources live in branding/ and are edited as text; the PNGs are derived
# and regenerated by this command. That way the branding is versioned in a
# meaningful way instead of as opaque binary files.
#
# Rendering is done by rsvg-convert from librsvg. It is already on the build
# host as a dependency of gtk, so a separate imagemagick is not needed.
set -euo pipefail

LUNA_SRC=${LUNA_SRC:-/mnt/c/Users/anyah/Documents/Claudes work/luna}
SVG="$LUNA_SRC/branding"

msg() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m!!!\033[0m %s\n' "$*" >&2; exit 1; }

command -v rsvg-convert >/dev/null || die "rsvg-convert is missing (package librsvg)"

render() { # source width height destination
  rsvg-convert -w "$2" -h "$3" -o "$4" "$1"
  printf '  %-52s %s\n' "$(basename "$4")" "$(du -h "$4" | cut -f1)"
}

msg "Boot menu splash (syslinux, BIOS)"
render "$SVG/splash.svg" 640 480 "$LUNA_SRC/iso/syslinux/splash.png"

# 16:9, not 4:3. GRUB stretches the background across the whole screen without
# preserving the aspect ratio: a moon rendered at 4:3 came out noticeably
# elliptical on a wide screen.
msg "GRUB bootloader background"
render "$SVG/splash.svg" 1920 1080 "$LUNA_SRC/pkg/luna-base/grub-background.png"

msg "Plymouth boot splash watermark"
render "$SVG/plymouth-watermark.svg" 200 200 "$LUNA_SRC/pkg/luna-base/plymouth-watermark.png"

msg "Done"
